### ISSUE TITLE
test

### ISSUE THREAD

**Issue by huikang** [kubernetes-analysis/kubernetes-analysis#86]
```release-note
Introduces a new GCE specific cluster creation variable KUBE_PROXY_DISABLE. When set to true, this will skip over the creation of kube-proxy (whether the daemonset or static pod). This can be used to control the lifecycle of kube-proxy separately from the lifecycle of the nodes.
```

**Comment by huikang** [comment]
Hi, @saschagrunert , thanks for sharing this useful tool. I copied the release note from https://github.com/kubernetes/kubernetes/pull/91977

Although the tool successfully predicts this is a release notes, however it is labeled as **kind/bug**, instead of **kind/feature**. Could you help me to understand if this is a misprediction or expected result? Thanks.

**Comment by saschagrunert** [comment]
Hey @huikang, thank you for testing the bot. :pray: The linked PR is not labeled as `kind/bug` from what I can see, so the prediction of 12% seems correct to me. We update the data on a daily basis and this result will be used for the training.

**Comment by saschagrunert** [comment]
Closing, feel free to reopen if the issue still exist
/close
